version: '3.9'
services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server_container
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=StrongP@ssw0rd2025
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "StrongP@ssw0rd2025" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./init:/scripts
    command: >
      /opt/mssql-tools/bin/sqlcmd -S db -U sa -P StrongP@ssw0rd2025 -Q "CREATE DATABASE AuthDb"

volumes:
  sqlserver_data: